#!/usr/bin/env node

//for views to either have a base of /prod/ or /
process.env.local = true;

/**
 * Get port from environment and store in Express.
 */

//eslint-disable-next-line
for (var i in process.argv) {
	let thisArg = process.argv[i];
	let nextArg = process.argv[i - -1];
	
	switch (thisArg) {
		case '--port':
			process.env.PORT = nextArg;
			break;
		case '--production':
			console.log('Setting process.env.NODE_ENV=production');
			process.env.NODE_ENV = 'production';
			break;
		default:
			if (thisArg.substring(0, 2) == '--') {
				console.log(`Setting process.env.${thisArg.substring(2)}=${nextArg}`);
				process.env[thisArg.substring(2)] = nextArg;
			}
			break;
	}
}

/**
 * Module dependencies.
 */

var app = require('./app');
var http = require('http');


var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
	var port = parseInt(val, 10);

	if (isNaN(port)) {
		// named pipe
		return val;
	}

	if (port >= 0) {
		// port number
		return port;
	}

	return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
	if (error.syscall !== 'listen') {
		throw error;
	}

	var bind = typeof port === 'string'
		? 'Pipe ' + port
		: 'Port ' + port;

	// handle specific listen errors with friendly messages
	switch (error.code) {
		case 'EACCES':
			console.error(bind + ' requires elevated privileges');
			process.exit(1);
			break;
		case 'EADDRINUSE':
			console.error(bind + ' is already in use');
			process.exit(1);
			break;
		default:
			throw error;
	}
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
	var addr = server.address();
	var bind = typeof addr === 'string'
		? 'pipe ' + addr
		: 'port ' + addr.port;
	console.log('Listening on ' + bind);
}
